-- Vaciar Papelera
PURGE RECYCLEBIN;
-- Tablas
START Estructura_y_restricciones_declarativas/Tablas.sql
-- Atributos
START Estructura_y_restricciones_declarativas/Atributos.sql
-- Llaves Primarias
START Estructura_y_restricciones_declarativas/Primarias.sql
-- Llaves Unicas
START Estructura_y_restricciones_declarativas/Unicas.sql
-- Llaves Foraneas  
START Estructura_y_restricciones_declarativas/Foraneas.sql
-- PoblarOK
START Estructura_y_restricciones_declarativas/PoblarOK.sql
-- PoblarNoOK
START Estructura_y_restricciones_declarativas/PoblarNoOK.sql
-- Consultas
START Estructura_y_restricciones_declarativas/Consultas.sql
-- Tuplas
START Restricciones_Declarativas_Procedimentales_y_Automatizacion/Tuplas.sql
-- TuplasOK
START Restricciones_Declarativas_Procedimentales_y_Automatizacion/TuplasOk.sql
-- TuplasNoOK
START Restricciones_Declarativas_Procedimentales_y_Automatizacion/TuplasNoOK.sql
-- Acciones
START Restricciones_Declarativas_Procedimentales_y_Automatizacion/Acciones.sql
-- AccionesOK
START Restricciones_Declarativas_Procedimentales_y_Automatizacion/AccionesOK.sql
-- Disparadores
START Restricciones_Declarativas_Procedimentales_y_Automatizacion/Disparadores.sql
-- DisparadoresOK
START Restricciones_Declarativas_Procedimentales_y_Automatizacion/DisparadoresOK.sql
-- DisparadoresNoOK
START Restricciones_Declarativas_Procedimentales_y_Automatizacion/DisparadoresNoOK.sql
-- Indices
START Indices_y_vistas/Indices.sql
-- Vistas
START Indices_y_vistas/Vistas.sql
-- IndicesVistasOK
START Indices_y_vistas/IndicesVistasOK.sql
-- CRUDE
START Componentes/CRUDE.sql
-- CRUDI
START Componentes/CRUDI.sql
-- CRUDOK
START Componentes/CRUDOK.sql
-- CRUDNOOK
START Componentes/CRUDNoOK.sql
-- ActoresE
START Seguridad/ActoresE.sql
-- ActoresI
START Seguridad/ActoresI.sql
-- Seguridad
START Seguridad/Seguridad.sql
-- SeguridadOK
START Seguridad/SeguridadOK.sql
-- XSeguridad
START Seguridad/XSeguridad.sql
-- XCRUD
START Componentes/XCRUD.sql
-- XIndicesVistas
START Indices_y_vistas/XIndicesVistas.sql
-- XDisparadores
START Restricciones_Declarativas_Procedimentales_y_Automatizacion/XDisparadores.sql
-- XPoblar
START Estructura_y_restricciones_declarativas/XPoblar.sql
-- XTablas
START Estructura_y_restricciones_declarativas/XTablas.sql
-- Vaciar Papelera
PURGE RECYCLEBIN;