-- XTablas
DROP TABLE Carreras CASCADE CONSTRAINTS;
DROP TABLE Clasificaciones CASCADE CONSTRAINTS;
DROP TABLE Practicas CASCADE CONSTRAINTS;
DROP TABLE Eventos CASCADE CONSTRAINTS;
DROP TABLE VehiculosPorTorneo CASCADE CONSTRAINTS;
DROP TABLE VehiculosDeJuegos CASCADE CONSTRAINTS;
DROP TABLE CircuitosDisponibles CASCADE CONSTRAINTS;
DROP TABLE Torneos CASCADE CONSTRAINTS;
DROP TABLE Organizadores CASCADE CONSTRAINTS;
DROP TABLE Juegos CASCADE CONSTRAINTS;
DROP TABLE Circuitos CASCADE CONSTRAINTS;
DROP TABLE Vehiculos CASCADE CONSTRAINTS;
DROP TABLE Usuarios CASCADE CONSTRAINTS;