-- ELIMINAR VISTAS
DROP VIEW v_inscripciones_por_torneo;
DROP VIEW v_estadisticas_carreras;
DROP VIEW v_torneos_por_organizador;
DROP VIEW v_eventos_torneos_detalle;
DROP VIEW v_vehiculos_por_juego;
DROP VIEW v_circuitos_por_juego;
DROP VIEW v_vehiculos_torneo;
DROP VIEW v_circuitos_torneo;
DROP VIEW v_resumen_torneo_organizador;
DROP VIEW v_torneos_por_plataforma;
DROP VIEW v_actividad_mensual_torneos;
DROP VIEW v_circuitos_mas_usados;
DROP VIEW v_juegos_populares;

-- ELIMINAR ÍNDICES
DROP INDEX idx_torneos_estado;
DROP INDEX idx_eventos_estado;
DROP INDEX idx_torneos_organizador;
DROP INDEX idx_torneos_juego;
DROP INDEX idx_eventos_circuito;
DROP INDEX idx_torneos_fecha_inicio;
DROP INDEX idx_torneos_org_estado;
DROP INDEX idx_torneos_juego_estado;
DROP INDEX idx_circdisp_juego;
DROP INDEX idx_circdisp_circuito;
DROP INDEX idx_vehjuego_juego;
DROP INDEX idx_vehtorneo_torneo;
DROP INDEX idx_usuarios_pais;
DROP INDEX idx_vehiculos_categoria;
DROP INDEX idx_circuitos_pais;
DROP INDEX idx_carreras_torneo;
DROP INDEX idx_clasificaciones_torneo;
DROP INDEX idx_practicas_torneo;