DROP PACKAGE PK_MANTENER_VEHICULO;
DROP PACKAGE PK_MANTENER_CIRCUITO;
DROP PACKAGE PK_MANTENER_JUEGO;
DROP PACKAGE PK_MANTENER_ORGANIZADOR;
DROP PACKAGE PK_MANTENER_CARRERA;
DROP PACKAGE PK_MANTENER_CLASIFICACION;
DROP PACKAGE PK_MANTENER_PRACTICA;
DROP PACKAGE PK_MANTENER_TORNEO;